### ISSUE TITLE
glitch and graphical problem

### ISSUE THREAD

**Issue by ThunderHero2021** [HimDek/yuzu-Early-Access-Launcher#18]
https://github.com/HimDek/yuzu-Early-Access-Launcher/assets/161940521/2a103cbe-632f-406f-ad19-693c67029534

This happened when i play this game on yuzu version 4176. So, can you solve this issue please as soon as possible?

al_hussain@msn.com

Kind regards

**Comment by HimDek** [comment]
This is not a repository for the emulatior but only the launcher.
